spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net/heroku_86b6e8fc0bd3bb1?reconnect=true
    username: b1cd525c86c3d2
    password: 1436d536
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
  mvc.view.prefix: /WEB-INF/views/
  mvc.view.suffix: .jsp
  resources.static-locations: classpath:/images/,classpath:/jsp/